#!/bin/zsh
source ./scripts/setup_env $1

echo -e "\x1b[1m"
echo '     _____       ___                    ______      ___  '
echo '    /     \     /   |   \    /         /      |   /    | '
echo '   /      |    /    |    \  /         /      /        /  '
echo '  /      /    /_____|     \/         /      /       _"   '
echo ' /      /    /      |     /         /      /      -"     '
echo '/____.-^    /       |    /         |______/    _-_____   '
echo '                                                         '
echo -en '\x1b[0m'
echo

if [[ $RUN_C == true ]]; then
    echo "C"
    ./scripts/run/c_file day02/solve.c
    echo
fi

if [[ $RUN_CS == true ]]; then
    echo "C#"
    ./scripts/run/c#_file day02/Solve.cs
    echo
fi

if [[ $RUN_GO == true ]]; then
    echo "Go"
    /usr/bin/time -h go run day02/solve.go
    echo
fi
