#!/bin/zsh
echo -e "\x1b[1m"
echo '     _____       ___                    ______      ___  '
echo '    /     \     /   |   \    /         /      |       /  '
echo '   /      |    /    |    \  /         /      /       /   '
echo '  /      /    /_____|     \/         /      /       /    '
echo ' /      /    /      |     /         /      /       /     '
echo '/____.-^    /       |    /         |______/    ___/___   '
echo '                                                         '
echo -en '\x1b[0m'
echo

echo "C"
./scripts/run/c_file day01/solve.c
echo

echo "C#"
./scripts/run/c#_file day01/Solve.cs
echo

echo "Go"
/usr/bin/time -h go run day01/solve.go
echo 

echo "Java"
/usr/bin/time -h java day01/Solve.java
echo

echo "Python"
/usr/bin/time -h python3 day01/solve.py
echo

echo "Rust"
./scripts/run/rust_file day01/solve.rs
echo

echo "Typescript"
/usr/bin/time -h npx ts-node day01/solve.ts
echo
