#!/bin/zsh
source ./scripts/setup_env $1

echo -e "\x1b[1m"
echo '     _____       ___                    ______           '
echo '    /     \     /   |   \    /         /      |   /    / '
echo '   /      |    /    |    \  /         /      /   /    /  '
echo '  /      /    /_____|     \/         /      /   *----/   '
echo ' /      /    /      |     /         /      /        /    '
echo '/____.-^    /       |    /         |______/        /     '
echo '                                                         '
echo -en '\x1b[0m'
echo


if [[ $RUN_C == true ]]; then
    echo "C"
    ./scripts/run/c_file day04/solve.c
    echo
fi


if [[ $RUN_RUST == true ]]; then
    echo "Rust"
    ./scripts/run/rust_file day04/solve.rs
    echo
fi

