#!/bin/zsh
echo -e "\x1b[1m"
echo '     _____       ___                    ______     _____ '
echo '    /     \     /   |   \    /         /      |        / '
echo '   /      |    /    |    \  /         /      /        /  '
echo '  /      /    /_____|     \/         /      /   -----/   '
echo ' /      /    /      |     /         /      /        /    '
echo '/____.-^    /       |    /         |______/   _____/     '
echo '                                                         '
echo -en '\x1b[0m'
echo

echo "Java"
./scripts/run/java_file day03/Solve.java 
echo

echo "Rust"
./scripts/run/rust_file day03/solve.rs
echo
