#!/bin/zsh
source ./scripts/setup_env $1

echo -e "\x1b[1m"
echo '     _____       ___                    ______     _____ '
echo '    /     \     /   |   \    /         /      |        / '
echo '   /      |    /    |    \  /         /      /        /  '
echo '  /      /    /_____|     \/         /      /   -----/   '
echo ' /      /    /      |     /         /      /        /    '
echo '/____.-^    /       |    /         |______/   _____/     '
echo '                                                         '
echo -en '\x1b[0m'
echo

if [[ $RUN_JAVA == true ]]; then
    echo "Java"
    ./scripts/run/java_file day03/Solve.java 
    echo
fi

if [[ $RUN_RUST == true ]]; then
    echo "Rust"
    ./scripts/run/rust_file day03/solve.rs
    echo
fi
