#!/bin/zsh
echo -e "\x1b[1m"
echo '     _____       ___                    ___      ______  '
echo '    /     \     /   |   \    /            /     /      | '
echo '   /      |    /    |    \  /            /     /      /  '
echo '  /      /    /_____|     \/            /     /      /   '
echo ' /      /    /      |     /            /     /      /    '
echo '/____.-^    /       |    /         ___/___  |______/     '
echo '                                                         '
echo -en '\x1b[0m'
echo

echo "Rust"
./scripts/run/rust_crate day10
echo
