#!/bin/zsh
echo -e "\x1b[1m"
echo '     _____       ___                    ______      ___  '
echo '    /     \     /   |   \    /         /      |       /  '
echo '   /      |    /    |    \  /         /      /       /   '
echo '  /      /    /_____|     \/         /      /       /    '
echo ' /      /    /      |     /         /      /       /     '
echo '/____.-^    /       |    /         |______/    ___/___   '
echo '                                                         '
echo -en '\x1b[0m'
echo

echo "C"
./scripts/run/c_file day1/solve.c
echo

echo "C#"
./scripts/run/c#_file day1/Solve.cs
echo

echo "Go"
go run day1/solve.go
echo 

echo "Java"
java day1/Solve.java
echo

echo "Python"
python3 day1/solve.py
echo

echo "Rust"
./scripts/run/rust_file day1/solve.rs
echo

echo "Typescript"
npx ts-node day1/solve.ts
echo
