#!/bin/zsh
echo -e "\x1b[107m\x1b[1m\x1b[30m"
echo '     _____       ___                    ______      ___  '
echo '    /     \     /   |   \    /         /      |   /    | '
echo '   /      |    /    |    \  /         /      /        /  '
echo '  /      /    /_____|     \/         /      /       _"   '
echo ' /      /    /      |     /         /      /      -"     '
echo '/____.-^    /       |    /         |______/    _-_____   '
echo -e '\n\x1b[0m'
echo

echo "C"
./run_c_file day2/solve.c
echo

echo "C#"
./run_c#_file day2/Solve.cs
echo

echo "Python"
python3 day2/solve.py
echo
