#!/bin/zsh
echo -e "\x1b[107m\x1b[1m\x1b[30m"
echo '     _____       ___                    ______     _____ '
echo '    /     \     /   |   \    /         /      |        / '
echo '   /      |    /    |    \  /         /      /        /  '
echo '  /      /    /_____|     \/         /      /   -----/   '
echo ' /      /    /      |     /         /      /        /    '
echo '/____.-^    /       |    /         |______/   _____/     '
echo -e '\n\x1b[0m'
echo

echo "Java"
./run_java_file day3/Solve.java 
echo

echo "Rust"
./run_rust_file day3/solve.rs
echo
