#!/bin/zsh
echo -e "\x1b[1m"
echo '     _____       ___                    ______           '
echo '    /     \     /   |   \    /         /      |   /    / '
echo '   /      |    /    |    \  /         /      /   /    /  '
echo '  /      /    /_____|     \/         /      /   *----/   '
echo ' /      /    /      |     /         /      /        /    '
echo '/____.-^    /       |    /         |______/        /     '
echo '                                                         '
echo -en '\x1b[0m'
echo

echo "C"
./scripts/run/c_file day4/solve.c
echo

echo "Rust"
./scripts/run/rust_file day4/solve.rs
echo
