#!/bin/zsh
echo -e "\x1b[1m"
echo '     _____       ___                    ______     _____ '
echo '    /     \     /   |   \    /         /      |   /    / '
echo '   /      |    /    |    \  /         /      /   /    /  '
echo '  /      /    /_____|     \/         /      /   *----*   '
echo ' /      /    /      |     /         /      /   /    /    '
echo '/____.-^    /       |    /         |______/   /____/     '
echo '                                                         '
echo -en '\x1b[0m'
echo

echo "Rust"
./scripts/run/rust_crate day08
echo

echo "Typescript"
/usr/bin/time -h npx ts-node day08/solve.ts
echo
